### ISSUE TITLE
"Error from chokidar" when Starting Web Client

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr-web#107]
When I start the web client with `npm run dev:start`, I get a bunch of errors beginning with "Error from chokidar":
```
...
Error from chokidar (/home/vma/container-jfr-web/node_modules/@patternfly/react-tokens/dist/js): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/vma/container-jfr-web/node_modules/@patternfly/react-tokens/dist/js/l_split.js'
Error from chokidar (/home/vma/container-jfr-web/node_modules/@patternfly/react-tokens/dist/js): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/vma/container-jfr-web/node_modules/@patternfly/react-tokens/dist/js/l_split_m_gutter_MarginRight.d.ts'
Error from chokidar (/home/vma/container-jfr-web/node_modules/@patternfly/react-tokens/dist/js): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/vma/container-jfr-web/node_modules/@patternfly/react-tokens/dist/js/l_split_m_gutter_MarginRight.js'
...
```
The web client works as expected though. Is this anything to worry about? @Alexjsenn told me he gets the same errors.

**Comment by andrewazores** [comment]
Increase your system inotify limits (probably max_user_watches):

https://github.com/paulmillr/chokidar/issues/294

It isn't a significant issue because the Webpack dev server is only used for development. In an actual deployment the web-client is just some static files that are served out by the ContainerJFR webserver, so there is no Chokidar and no filesystem watchers.
